language: python

python:
  - 3.7

services:
  - postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=ProjectRecipe.settings

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE recipedb;" -U postgres

script:
  - python manage.py wait_for_db
  - python manage.py migrate
  - python manage.py test